---
  - name: Generate RSA key
    command: openssl genrsa -out {{ item.0.privkey_path }} {{ ssl_certs_key_size }} creates={{ item.0.privkey_path }}
    when: item.1
    with_together:
      - "{{ ssl_certs }}"
      - "{{ ssl_certs_requires_creation }}"

  - name: RSA key file ownership
    file: path={{ item.0.privkey_path }} owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode={{ ssl_certs_mode }}
    when: item.1
    with_together:
      - "{{ ssl_certs }}"
      - "{{ ssl_certs_requires_creation }}"

  - name: Generate CSR
    command: openssl req -new -sha256 -subj "{{ item.0.fields }}" -key {{ item.0.privkey_path }} -out {{ item.0.csr_path }} creates={{ item.0.csr_path }}
    when: item.1
    with_together:
      - "{{ ssl_certs }}"
      - "{{ ssl_certs_requires_creation }}"

  - name: CSR file ownership
    file: path={{ item.0.csr_path }} owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode={{ ssl_certs_mode }}
    when: item.1
    with_together:
      - "{{ ssl_certs }}"
      - "{{ ssl_certs_requires_creation }}"

  - name: Generate self-signed SSL certificate
    command: openssl req -nodes -x509 -days {{ item.0.expiration_days|default("365") }} -in {{ item.0.csr_path }} -key {{ item.0.privkey_path }} -out {{ item.0.cert_path }} -extensions v3_ca creates={{ item.0.cert_path }}
    when: item.1 and item.0.generate_self_signed|default(true)
    with_together:
      - "{{ ssl_certs }}"
      - "{{ ssl_certs_requires_creation }}"

  - name: Self-signed SSL certificate file ownership
    file: path={{ item.0.cert_path }} owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode={{ ssl_certs_mode }}
    when: item.1 and item.0.generate_self_signed|default(true)
    with_together:
      - "{{ ssl_certs }}"
      - "{{ ssl_certs_requires_creation }}"
